name: Update gzachos.dev website

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  update_dev_site:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to gzachos.dev
      uses: actions/checkout@main
      with:
        repository: gzachos/gzachos.dev
        token: ${{ secrets.DEV_REPO_PAT }}
        path: .
    - name: Show files
      run: ls -l
    - name: Sync repos
      run: ./update-website.sh
    - name: Check git status
      run: git status
    - name: Push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated $(date +%Y%m%d_%H%M)"
        git push
