name: Automatic workflow

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  update_dev_site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        repository: gzachos/gzachos.dev
        path: .
    - name: Show files
      run: ls -l
    - name: Show path
      run: pwd
    - name: Enter repo
      run: cd gzachos.dev
    - name: Sync repos
      run: ./update-website.sh
